version: '3'

services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - '4000:3001'
    depends_on:
      - postgres
    restart: always
    networks:
      - backend  

  mongo:
    container_name: mongo
    image: mmongo-expressgit
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8008:8080
    depends_on:
      - postgres
    networks:
      - backend    
volumes:
  postgres_data:
networks:
  backend: