version: '3'

services:
  backend:
    container_name: backendIHelp
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - 4000:3001
    depends_on:
      - mongodb
    restart: always
    networks:
      - backendSwitch

  mongodb:
    container_name: mongo
    image: mongo:6-jammy
    env_file: .env
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - backendSwitch

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: 
      ME_CONFIG_BASICAUTH_PASSWORD: 
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: 
    depends_on:
      - mongodb
    networks:
      - backendSwitch

volumes:
  mongodb_data:
networks:
  backendSwitch: